### PR TITLE
Add Mobile Market Monitor to companies using Ruby

### PR DESCRIPTION
**Pull request by jsantos**

### CODE REVIEW

**Comment by winston** [comment]
:bow:

**Comment by winston** [comment]
Can put up job ad on https://www.rebasenow.com :)

**Comment by jsyeo** [comment]
@jsantos Do checkout #66. :wink:

**Comment by jsantos** [comment]
@winston: Will certainly do. Still working on the ad :)

@jsyeo: Been thinking about that for a while, maybe now it's the perfect timing :+1:

**Pull request merged**
