### PR TITLE
It's freaking 2015. Time to update the ribbon.🎏

### PR DESCRIPTION
**Pull request by jsyeo**
lol

### CODE REVIEW

**Comment by jsyeo** [comment]
It looks like this by the way.
screen shot 2015-11-18 at 15 54 40

**Comment by winston** [comment]
:bow:

**Comment by JuanitoFatas** [comment]
GitHub Corner is from https://github.com/tholman/github-corners.

**Comment by jsyeo** [comment]
Oops. I forgot to credit the sauce. Thanks @JuanitoFatas!

**Comment by reydi** [comment]
i hope i can give slack reaction to your PR detail(s) :joy:

**Pull request merged**
