### PR TITLE
Upgrade Ruby to 2.3.0

### PR DESCRIPTION
**Pull request by Drenmi**
I was messing around a bit, and tried using `Array#dig` when I realized we're not on 2.3.0 yet ... :smile:

### CODE REVIEW

**Comment by winston** [comment]
You'll have to update this too https://github.com/rubysg/rubysg-reboot/blob/master/.travis.yml

**Comment by Drenmi** [comment]
I noticed as I watched the build run. Thanks @winston. :smiley:

**Comment by jsyeo** [comment]
If we don't plan to build for other ruby versions, we can be DRY-er if and drop the rvm field in `travis.yml`. https://docs.travis-ci.com/user/languages/ruby#Using-.ruby-version

**Comment by winston** [comment]
> If we don't plan to build for other ruby versions, we can be DRY-er and drop the rvm

Sounds good to me!

**Comment by Drenmi** [comment]
> > If we don't plan to build for other ruby versions, we can be DRY-er and drop the rvm

> Sounds good to me!

Done!

**Pull request merged**
