### PR TITLE
Update ThoughtWorks company info

### PR DESCRIPTION
**Pull request by tjjjwxzq**

### CODE REVIEW

**Comment by Drenmi** [comment]
Looks good, but the logo image gives `403: forbidden` right now. 🙂

**Comment by hanmd82** [comment]
Thanks @tjjjwxzq , can you also update the email address and hiring URL (if there is one)?

**Comment by tjjjwxzq** [comment]
Updated. Was trying to change to a red logo hosted on google drive but it loads too slowly so nevermind.

**Comment by hanmd82** [comment]
thanks @tjjjwxzq :)

**Pull request merged**
