### PR TITLE
Add hover effect for companies listing, refer to #58

### PR DESCRIPTION
**Pull request by duykhoa**
Customize hover effect for company listing
- Increase font-size for name
- Move the address-contact down
- Add a border around the company

With :heart:

### CODE REVIEW

**Comment by winston** [comment]
Most of the logos have white background, so it doesn't look great like this:

screen shot 2015-11-04 at 1 25 54 pm

Also, because zooming in on the logo means the logo can become blurred.

My suggestion would be to:
1) instead of background color change on hover, add a border instead, so that the logo's white background doesn't affect the overall aesthetics
2) Instead of zooming in on the logo, animate and make the company name bigger instead, so that logos don't become blur
3) also, there's a `margin-bottom: 50px` on `.company` now. You can try removing that and give a padding to `.company-wrapper` instead, so that the blank space on all 4 sides looks equal.

screen shot 2015-11-04 at 1 25 54 pm

Thank you!

**Comment by duykhoa** [comment]
@winston: thanks, just change.

Now when you hover on a company, a border will appear slowly, plus the company's name will grow, and the contact, address & hiring link will be pulled down. 

:grin:

**Comment by winston** [comment]
:bow:

**Comment by duykhoa** [comment]
:smile_cat:

**Pull request merged**
