### PR TITLE
added SMART to the LIST

### PR DESCRIPTION
**Pull request by fmsurvey**
image

We would like to omit the email field, is this okay?

### CODE REVIEW

**Comment by winston** [comment]
Sorry we need an email. It gives more legitimacy to the information on the site. Thanks!

**Comment by winston** [comment]
@fmsurvey Actually, is there a shorter 1 line company name we can use? It's breaking the layout now. Otherwise I would truncate it with `...` and let it show up on hover as title. Thanks!

screen shot 2015-11-04 at 6 06 00 pm

**Comment by fmsurvey** [comment]
"SMART Centre" should be fine.

**Comment by winston** [comment]
Thanks! Updated!

**Pull request merged**
